- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  	- name: Import VPC variables
  	  include_vars: vars/vpc_setup

  	- name: Create 3T VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: 3Tvpcout
      
    - debug:
        var: 3Tvpcout

    - name: create public subnet1 for web in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub1cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-WEB-1a
      register: 3Tpubsub1zone1web_out
    
    - name: create public subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub2cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-WEB-1b
      register: 3Tpubsub1zone2web_out

    - name: create public subnet3 for app in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub3cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-APP-1a
      register: 3Tpubsub3zone1app_out
    
    - name: create public subnet4 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-APP-1b
      register: 3Tpubsub4zone2app_out

    - name: create public subnet5 for db in zone1
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubsub5cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-DB-1a
      register: 3Tpubsub5zone1db_out
    
    - name: create public subnet6 for db in zone2
      ec2_vpc_subnet:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubsub4cidr}}"
        map_public: yes
        resource_tags:
          Name: 3T-DB-1b
      register: 3Tpubsub6zone2db_out

    - name: Internet Gateway Setup
      ec2_vpc_igw: 
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags: 
          Name: 3T_IGW
      register: 3T_igw_out
     
    - name: Setup Public Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: 3T-PUBLIC-RT
        subnets:
          - "{{3Tpubsub1zone1web_out.subnet.id}}"
          - "{{3Tpubsub1zone2web_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{3T_igw_out.gateway_id}}"
      register: 3T_pubRT_out
      
    - name: Create new NAT gateway fro 3T webapp
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{3Tpubsub1zone1web_out.subnet.id}}"
        wait: yes
        region: "{{region}}"
        if_exist_do_not_create: true
      register: 3T_NATGW_out
    
    - name: Setup private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{3Tvpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: 3T-PRIVATE-RT
        subnets:
          - "{{3Tpubsub3zone1app_out.subnet.id}}"
          - "{{3Tpubsub4zone2app_out.subnet.id}}"
          - "{{3Tpubsub5zone1db_out.subnet.id}}"
          - "{{3Tpubsub6zone2db_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{3T_NATGW_out.nat_gateway_id}}"
      register: 3T_privRT_out
      
    - debug: 
        var: "{{item}}"
      loop:
        - 3Tvpcout.vpc.id
        - 3Tpubsub3zone1app_out.subnet.id
        - 3Tpubsub4zone2app_out.subnet.id
        - 3Tpubsub5zone1db_out.subnet.id
        - 3Tpubsub6zone2db_out.subnet.id
        - 3Tpubsub1zone1web_out.subnet.id
        - 3Tpubsub1zone2web_out.subnet.id
        - 3T_igw_out.gateway_id
        - 3T_pubRT_out.route_table.id
        - 3T_NATGW_out.nat_gateway_id
        - 3T_privRT_out.route_table.id
      
    - set_fact:
         vpcid: "{{3Tvpcout.vpc.id}}"
         pubsub1id: "{{3Tpubsub1zone1web_out.subnet.id}}"
         pubsub2id: "{{3Tpubsub1zone2web_out.subnet.id}}"
         pubsub3id: "{{3Tpubsub3zone1app_out.subnet.id.subnet.id}}"
         privsub1id: "{{3Tpubsub4zone2app_out.subnet.id.subnet.id}}"
         privsub2id: "{{3Tpubsub5zone1db_out.subnet.id}}"
         privsub3id: "{{3Tpubsub6zone2db_out.subnet.id}}"
         igwid: "{{3T_igw_out.gateway_id}}"
         pubRTid: "{{3T_pubRT_out.route_table.id}}"
         NATGWid: "{{3T_NATGW_out.nat_gateway_id}}"
         privRTid: "{{3T_privRT_out.route_table.id}}"
         cacheable: yes
          
    - name: create variables file for VPC output
      copy: 
        content: "vpcid: {{3Tvpcout.vpc.id}}\npubsub1id: {{3Tpubsub1zone1web_out.subnet.id}}\npubsub2id: {{3Tpubsub1zone2web_out.subnet.id}}\npubsub3id: {{3Tpubsub3zone1app_out.subnet.id.subnet.id}}\nprivsub1id: {{3Tpubsub4zone2app_out.subnet.id.subnet.id}}\nprivsub2id: {{3Tpubsub5zone1db_out.subnet.id}}\nprivsub3id: {{3Tpubsub6zone2db_out.subnet.id}}\nigwid: {{3T_igw_out.gateway_id}}\npubRTid: {{3T_pubRT_out.route_table.id}}\nNATGWid: {{3T_NATGW_out.nat_gateway_id}}\nprivRTid: {{3T_privRT_out.route_table.id}}\n"
        dest: vars/output_vars